/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Model.MYSQL;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pasindu
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public AddEmployee() {
        initComponents();
        loadTable();

    }
    
    public void loadTable() {
        try {
            
            ResultSet resultSet = (ResultSet) MYSQL.search("SELECT * FROM employee");
            ResultSet count = MYSQL.search("SELECT COUNT(*) FROM employee");

              DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
            model.setRowCount(0);

         

      
            while (resultSet.next()) {
                Vector<String> v = new Vector();
                v.add(resultSet.getString("employee_ID"));
                v.add(resultSet.getString("name"));
                v.add(resultSet.getString("address"));
                v.add(resultSet.getString("mobile_no"));
                v.add(resultSet.getString("possition"));
                v.add(resultSet.getString("salary"));

                model.addRow(v);
                employeeTable.setModel(model);
            }
            
             if (count.next()) {
                int cnt = count.getInt(1);
                countbox.setText(String.valueOf(cnt));
            }

        } catch (Exception e) {
        }
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        emobile = new javax.swing.JTextField();
        eaddress = new javax.swing.JTextField();
        esalary = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        eposs = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        searchbox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        countbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        logoutbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD EMPLOYEE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/8666546_user_plus_icon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 60));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("SHOP BUDDY");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 33, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("EMPLOYEE ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 173, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("EMPLOYEE NAME");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 233, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("ADDRESS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 286, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("MOBILE NO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("JOB POSSITION");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 401, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("SALARY");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 441, -1, -1));
        jPanel2.add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 174, 188, -1));

        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        jPanel2.add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 233, 188, -1));
        jPanel2.add(emobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 330, 180, -1));
        jPanel2.add(eaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 279, 188, -1));
        jPanel2.add(esalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 441, 180, -1));

        addbtn.setBackground(new java.awt.Color(255, 255, 153));
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel2.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 519, -1, -1));

        updatebtn.setBackground(new java.awt.Color(255, 255, 153));
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel2.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 519, -1, -1));

        eposs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Manager", "Cashier", "Inventry Manager" }));
        jPanel2.add(eposs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 160, -1));

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("ADD EMPLOYEE");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 427, 580));

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel2.setText("ALL EMPLOYEE DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 16, -1, -1));

        employeeTable.setBackground(new java.awt.Color(255, 255, 204));
        employeeTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Address", "Mobile No", "Job Possition", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.setGridColor(new java.awt.Color(255, 102, 102));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 840, 410));

        searchbox.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 220, -1));

        searchbtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        countbox.setBackground(new java.awt.Color(255, 255, 153));
        countbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countbox.setBorder(null);
        jPanel1.add(countbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 60, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel10.setText("No of Employee : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, -1, -1));

        logoutbtn.setText("HOME");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, -1));

        logoutbtn1.setText("LOG OUT");
        logoutbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String employeid = eid.getText();
        String empname = ename.getText();
        String empadd = eaddress.getText();
        String empmobile = emobile.getText();
        String position = eposs.getSelectedItem().toString();
        String empsal = esalary.getText();

        if (employeid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee ID field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            eid.grabFocus();
        } else if (empname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee Name field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            ename.grabFocus();
        } else if (empadd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee Address field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            eaddress.grabFocus();
        }
        else if (empmobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee Mobile Number field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            emobile.grabFocus();
        }
        else if (empsal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Salary", "Warning", JOptionPane.WARNING_MESSAGE);
            esalary.grabFocus();
        }
        else {

            MYSQL.iud("INSERT INTO employee (employee_ID,name,address,mobile_no,possition,salary) VALUES('" + employeid + "','" + empname + "','" + empadd + "','" + empmobile + "','"+position+"', '"+empsal+"') ");
            eid.setText("");
            ename.setText("");
            eaddress.setText("");
            emobile.setText("");
//            eposs.setText("");
            esalary.setText("");
            loadTable();
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel ob = (DefaultTableModel) employeeTable.getModel();
         TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
         employeeTable.setRowSorter(obj);
         obj.setRowFilter(RowFilter.regexFilter(searchbox.getText()));
    }//GEN-LAST:event_searchbtnActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        // TODO add your handling code here:
        DefaultTableModel ob = (DefaultTableModel) employeeTable.getModel();
         TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
         employeeTable.setRowSorter(obj);
         obj.setRowFilter(RowFilter.regexFilter(searchbox.getText()));
    }//GEN-LAST:event_searchboxKeyReleased

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        // TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        int selectedRow = employeeTable.getSelectedRow();
        
        if (selectedRow != -1) {  // Ensure a row is selected
            try {
                String employeid = String.valueOf(employeeTable.getValueAt(selectedRow, 0));
                eid.setText(employeid);
                String empname = String.valueOf(employeeTable.getValueAt(selectedRow, 1));
                ename.setText(empname);
                String empadd = String.valueOf(employeeTable.getValueAt(selectedRow, 2));
                eaddress.setText(empadd);
                String empmobile = String.valueOf(employeeTable.getValueAt(selectedRow, 3));
                emobile.setText(empmobile);
                String empsal = String.valueOf(employeeTable.getValueAt(selectedRow, 5));
                esalary.setText(empsal);
                String position = String.valueOf(employeeTable.getValueAt(selectedRow, 4));
                eposs.setSelectedItem(position);

            } catch (Exception e) {
                // Handle potential exceptions
                
            }
        }
    }
    }//GEN-LAST:event_employeeTableMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String employeid = eid.getText();
        String empname = ename.getText();
        String empadd = eaddress.getText();
        String empmobile = emobile.getText();
        String position = eposs.getSelectedItem().toString();
        String empsal = esalary.getText();

        if (employeid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee ID field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            eid.grabFocus();
        } else if (empname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee Name field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            ename.grabFocus();
        } else if (empadd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee Address field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            eaddress.grabFocus();
        }
        else if (empmobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee Mobile Number field is empty", "Warning", JOptionPane.WARNING_MESSAGE);
            emobile.grabFocus();
        }
        else if (empsal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Salary", "Warning", JOptionPane.WARNING_MESSAGE);
            esalary.grabFocus();
        }
        else {

            MYSQL.iud("UPDATE employee SET name = '"+empname+"',address= '"+empadd+"',mobile_no = '"+empmobile+"',possition = '"+position+"',salary = '"+empsal+"' WHERE employee_ID = '"+employeid+"'");
            eid.setText("");
            ename.setText("");
            eaddress.setText("");
            emobile.setText("");
//          eposs.setText("");
            esalary.setText("");
            loadTable();
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        Adminhome AdminhomeWindow = new Adminhome();
        AdminhomeWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void logoutbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtn1ActionPerformed
        // TODO add your handling code here:
        Login LoginWindow = new Login();
        LoginWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField countbox;
    private javax.swing.JTextField eaddress;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField emobile;
    private javax.swing.JTable employeeTable;
    private javax.swing.JTextField ename;
    private javax.swing.JComboBox<String> eposs;
    private javax.swing.JTextField esalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton logoutbtn1;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
